name: flutter_common_form_validation
description: Flutter common form validation
version: 0.0.4
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0

dev_dependencies:
  lint: ^1.8.2
